### ISSUE TITLE
Can't execute on Linux - Ubuntu 14.04

### ISSUE THREAD

**Issue by kikukiks** [robertpallas/pgdeploy#2]
Error on execute:
/usr/bin/env: node --harmony: No such file or directory

Issue exists on Ubuntu 16.04 as well.

A workaround exists where pgdeploy can be run as follows:
$ node /usr/bin/pgdeploy

**Comment by robertpallas** [comment]
The Linux kernel does not support multiple arguments in shebangs. https://bbs.archlinux.org/viewtopic.php?id=168479

Will remove harmony flag.
